spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://sqlserver-dhkim1206.database.windows.net:1433;database=sqldb-dhkim1206;user=dhkim1206@sqlserver-dhkim1206;password=rlaehgud3737!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: dhkim1206
    password: rlaehgud3737!
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/HackerGround?serverTimezone=UTC&characterEncoding=UTF-8
  #    username: root
  #    password: Cksdud!0342

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
    show-sql: true



