name: Build and deploy JAR app to Azure Web App - dhkim1206

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Check MySQL Version
        run: mysql --version

      - name: Build with Gradle
        run: |
          cd CrawlingNotiServer
          ./gradlew clean build

          # Add the following lines to run tests separately
          echo "Running tests separately"
          ./gradlew test --stacktrace

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/CrawlingNotiServer/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dhkim1206'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8431408FC7D4498884C5D2E334C95F06 }}
          package: '*.jar'
